# Omniprof — config Streamlit
# https://docs.streamlit.io/develop/api-reference/configuration

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[server]
maxUploadSize = 200
enableCORS = false
enableWebsocketCompression = false
